### ISSUE TITLE
Transfer project

### ISSUE THREAD

**Issue by morganekmefjord** [scaleoutsystems/stackn#50]
Implement the transfer project to new user.
This will set the owner of the project to a new user.

## Components to do
- [x] Model updated
- [x] View updated
- [x] Function required to get POST information to perform the change
- [x] Frontend Function to prompt user for "Are you sure?  Y/N"

## Todo for later
- [ ] Later we need to regenerate keys and set them again if new user is asigned but that is overkill ATM
